<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WrkAcheminement', 'doctrine');

/**
 * BaseWrkAcheminement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_acheminement
 * @property string $num_acheminement
 * @property integer $suffix_colis
 * @property integer $nb_colis
 * @property string $tracking
 * @property string $ref_produit
 * @property string $code_emplacement_prise
 * @property string $code_emplacement_depose
 * @property string $delais
 * @property integer $id_utilisateur
 * @property string $date_fait
 * @property string $statut
 * @property string $demandeur
 * @property string $destinataire
 * @property string $designation
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property RefEmplacement $RefEmplacementPrise
 * @property RefEmplacement $RefEmplacementDepose
 * @property RefDestinataireAcheminement $RefDestinataireAcheminement
 * @property Doctrine_Collection $wrkAcheminementColis
 * 
 * @method integer                     getIdAcheminement()              Returns the current record's "id_acheminement" value
 * @method string                      getNumAcheminement()             Returns the current record's "num_acheminement" value
 * @method integer                     getSuffixColis()                 Returns the current record's "suffix_colis" value
 * @method integer                     getNbColis()                     Returns the current record's "nb_colis" value
 * @method string                      getTracking()                    Returns the current record's "tracking" value
 * @method string                      getRefProduit()                  Returns the current record's "ref_produit" value
 * @method string                      getCodeEmplacementPrise()        Returns the current record's "code_emplacement_prise" value
 * @method string                      getCodeEmplacementDepose()       Returns the current record's "code_emplacement_depose" value
 * @method string                      getDelais()                      Returns the current record's "delais" value
 * @method integer                     getIdUtilisateur()               Returns the current record's "id_utilisateur" value
 * @method string                      getDateFait()                    Returns the current record's "date_fait" value
 * @method string                      getStatut()                      Returns the current record's "statut" value
 * @method string                      getDemandeur()                   Returns the current record's "demandeur" value
 * @method string                      getDestinataire()                Returns the current record's "destinataire" value
 * @method string                      getDesignation()                 Returns the current record's "designation" value
 * @method timestamp                   getCreatedAt()                   Returns the current record's "created_at" value
 * @method timestamp                   getUpdatedAt()                   Returns the current record's "updated_at" value
 * @method RefEmplacement              getRefEmplacementPrise()         Returns the current record's "RefEmplacementPrise" value
 * @method RefEmplacement              getRefEmplacementDepose()        Returns the current record's "RefEmplacementDepose" value
 * @method RefDestinataireAcheminement getRefDestinataireAcheminement() Returns the current record's "RefDestinataireAcheminement" value
 * @method Doctrine_Collection         getWrkAcheminementColis()        Returns the current record's "wrkAcheminementColis" collection
 * @method WrkAcheminement             setIdAcheminement()              Sets the current record's "id_acheminement" value
 * @method WrkAcheminement             setNumAcheminement()             Sets the current record's "num_acheminement" value
 * @method WrkAcheminement             setSuffixColis()                 Sets the current record's "suffix_colis" value
 * @method WrkAcheminement             setNbColis()                     Sets the current record's "nb_colis" value
 * @method WrkAcheminement             setTracking()                    Sets the current record's "tracking" value
 * @method WrkAcheminement             setRefProduit()                  Sets the current record's "ref_produit" value
 * @method WrkAcheminement             setCodeEmplacementPrise()        Sets the current record's "code_emplacement_prise" value
 * @method WrkAcheminement             setCodeEmplacementDepose()       Sets the current record's "code_emplacement_depose" value
 * @method WrkAcheminement             setDelais()                      Sets the current record's "delais" value
 * @method WrkAcheminement             setIdUtilisateur()               Sets the current record's "id_utilisateur" value
 * @method WrkAcheminement             setDateFait()                    Sets the current record's "date_fait" value
 * @method WrkAcheminement             setStatut()                      Sets the current record's "statut" value
 * @method WrkAcheminement             setDemandeur()                   Sets the current record's "demandeur" value
 * @method WrkAcheminement             setDestinataire()                Sets the current record's "destinataire" value
 * @method WrkAcheminement             setDesignation()                 Sets the current record's "designation" value
 * @method WrkAcheminement             setCreatedAt()                   Sets the current record's "created_at" value
 * @method WrkAcheminement             setUpdatedAt()                   Sets the current record's "updated_at" value
 * @method WrkAcheminement             setRefEmplacementPrise()         Sets the current record's "RefEmplacementPrise" value
 * @method WrkAcheminement             setRefEmplacementDepose()        Sets the current record's "RefEmplacementDepose" value
 * @method WrkAcheminement             setRefDestinataireAcheminement() Sets the current record's "RefDestinataireAcheminement" value
 * @method WrkAcheminement             setWrkAcheminementColis()        Sets the current record's "wrkAcheminementColis" collection
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWrkAcheminement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wrk_acheminement');
        $this->hasColumn('id_acheminement', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('num_acheminement', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('suffix_colis', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('nb_colis', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('tracking', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('ref_produit', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('code_emplacement_prise', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('code_emplacement_depose', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('delais', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('id_utilisateur', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('date_fait', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('statut', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('demandeur', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('destinataire', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('designation', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RefEmplacement as RefEmplacementPrise', array(
             'local' => 'code_emplacement_prise',
             'foreign' => 'code_emplacement'));

        $this->hasOne('RefEmplacement as RefEmplacementDepose', array(
             'local' => 'code_emplacement_depose',
             'foreign' => 'code_emplacement'));

        $this->hasOne('RefDestinataireAcheminement', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id_destinataire_acheminement'));

        $this->hasMany('WrkColisAcheminement as wrkAcheminementColis', array(
             'local' => 'id_acheminement',
             'foreign' => 'id_acheminement'));
    }
}