<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WrkGroupWidget', 'doctrine');

/**
 * BaseWrkGroupWidget
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $id_widget
 * @property integer $ordre
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property sfGuardGroup $sfGuardGroup
 * @property RefWidget $RefWidget
 * 
 * @method integer        getGroupId()      Returns the current record's "group_id" value
 * @method integer        getIdWidget()     Returns the current record's "id_widget" value
 * @method integer        getOrdre()        Returns the current record's "ordre" value
 * @method timestamp      getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp      getUpdatedAt()    Returns the current record's "updated_at" value
 * @method sfGuardGroup   getSfGuardGroup() Returns the current record's "sfGuardGroup" value
 * @method RefWidget      getRefWidget()    Returns the current record's "RefWidget" value
 * @method WrkGroupWidget setGroupId()      Sets the current record's "group_id" value
 * @method WrkGroupWidget setIdWidget()     Sets the current record's "id_widget" value
 * @method WrkGroupWidget setOrdre()        Sets the current record's "ordre" value
 * @method WrkGroupWidget setCreatedAt()    Sets the current record's "created_at" value
 * @method WrkGroupWidget setUpdatedAt()    Sets the current record's "updated_at" value
 * @method WrkGroupWidget setSfGuardGroup() Sets the current record's "sfGuardGroup" value
 * @method WrkGroupWidget setRefWidget()    Sets the current record's "RefWidget" value
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWrkGroupWidget extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wrk_group_widget');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id_widget', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('ordre', 'integer', 2, array(
             'type' => 'integer',
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardGroup', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasOne('RefWidget', array(
             'local' => 'id_widget',
             'foreign' => 'id_widget'));
    }
}