<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RefEmplacementAcheminement', 'doctrine');

/**
 * BaseRefEmplacementAcheminement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code_emplacement
 * @property string $libelle
 * @property timestamp $updated_at
 * @property timestamp $created_at
 * 
 * @method string                     getCodeEmplacement()  Returns the current record's "code_emplacement" value
 * @method string                     getLibelle()          Returns the current record's "libelle" value
 * @method timestamp                  getUpdatedAt()        Returns the current record's "updated_at" value
 * @method timestamp                  getCreatedAt()        Returns the current record's "created_at" value
 * @method RefEmplacementAcheminement setCodeEmplacement()  Sets the current record's "code_emplacement" value
 * @method RefEmplacementAcheminement setLibelle()          Sets the current record's "libelle" value
 * @method RefEmplacementAcheminement setUpdatedAt()        Sets the current record's "updated_at" value
 * @method RefEmplacementAcheminement setCreatedAt()        Sets the current record's "created_at" value
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefEmplacementAcheminement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_emplacement_acheminement');
        $this->hasColumn('code_emplacement', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('libelle', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}