<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WrkInventaire', 'doctrine');

/**
 * BaseWrkInventaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_inventaire
 * @property integer $id_utilisateur
 * @property timestamp $heure_prise
 * @property string $ref_produit
 * @property string $code_emplacement
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property RefEmplacement $RefEmplacement
 * 
 * @method integer        getIdInventaire()     Returns the current record's "id_inventaire" value
 * @method integer        getIdUtilisateur()    Returns the current record's "id_utilisateur" value
 * @method timestamp      getHeurePrise()       Returns the current record's "heure_prise" value
 * @method string         getRefProduit()       Returns the current record's "ref_produit" value
 * @method string         getCodeEmplacement()  Returns the current record's "code_emplacement" value
 * @method timestamp      getCreatedAt()        Returns the current record's "created_at" value
 * @method timestamp      getUpdatedAt()        Returns the current record's "updated_at" value
 * @method RefEmplacement getRefEmplacement()   Returns the current record's "RefEmplacement" value
 * @method WrkInventaire  setIdInventaire()     Sets the current record's "id_inventaire" value
 * @method WrkInventaire  setIdUtilisateur()    Sets the current record's "id_utilisateur" value
 * @method WrkInventaire  setHeurePrise()       Sets the current record's "heure_prise" value
 * @method WrkInventaire  setRefProduit()       Sets the current record's "ref_produit" value
 * @method WrkInventaire  setCodeEmplacement()  Sets the current record's "code_emplacement" value
 * @method WrkInventaire  setCreatedAt()        Sets the current record's "created_at" value
 * @method WrkInventaire  setUpdatedAt()        Sets the current record's "updated_at" value
 * @method WrkInventaire  setRefEmplacement()   Sets the current record's "RefEmplacement" value
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWrkInventaire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wrk_inventaire');
        $this->hasColumn('id_inventaire', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_utilisateur', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('heure_prise', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('ref_produit', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('code_emplacement', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RefEmplacement', array(
             'local' => 'code_emplacement',
             'foreign' => 'code_emplacement'));
    }
}