<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdmSpool', 'doctrine');

/**
 * BaseAdmSpool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $id_spool
 * @property string $code_etiq
 * @property int $nb_etiq
 * @property string $parametres
 * @property string $imprimante
 * @property boolean $imprimee
 * 
 * @method int      getIdSpool()    Returns the current record's "id_spool" value
 * @method string   getCodeEtiq()   Returns the current record's "code_etiq" value
 * @method int      getNbEtiq()     Returns the current record's "nb_etiq" value
 * @method string   getParametres() Returns the current record's "parametres" value
 * @method string   getImprimante() Returns the current record's "imprimante" value
 * @method boolean  getImprimee()   Returns the current record's "imprimee" value
 * @method AdmSpool setIdSpool()    Sets the current record's "id_spool" value
 * @method AdmSpool setCodeEtiq()   Sets the current record's "code_etiq" value
 * @method AdmSpool setNbEtiq()     Sets the current record's "nb_etiq" value
 * @method AdmSpool setParametres() Sets the current record's "parametres" value
 * @method AdmSpool setImprimante() Sets the current record's "imprimante" value
 * @method AdmSpool setImprimee()   Sets the current record's "imprimee" value
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdmSpool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adm_spool');
        $this->hasColumn('id_spool', 'int', 11, array(
             'type' => 'int',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('code_etiq', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('nb_etiq', 'int', 2, array(
             'type' => 'int',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('parametres', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('imprimante', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('imprimee', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}