<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WrkMouvement', 'doctrine');

/**
 * BaseWrkMouvement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_mouvement
 * @property integer $id_utilisateur
 * @property timestamp $heure_prise
 * @property string $ref_produit
 * @property string $br_sap
 * @property string $code_emplacement
 * @property integer $retry
 * @property string $type
 * @property string $groupe
 * @property string $commentaire
 * @property string $quantite
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property RefEmplacement $RefEmplacement
 * @property WrkArrivageProduit $WrkArrivageProduit
 * 
 * @method integer            getIdMouvement()        Returns the current record's "id_mouvement" value
 * @method integer            getIdUtilisateur()      Returns the current record's "id_utilisateur" value
 * @method timestamp          getHeurePrise()         Returns the current record's "heure_prise" value
 * @method string             getRefProduit()         Returns the current record's "ref_produit" value
 * @method string             getBrSap()              Returns the current record's "br_sap" value
 * @method string             getCodeEmplacement()    Returns the current record's "code_emplacement" value
 * @method integer            getRetry()              Returns the current record's "retry" value
 * @method string             getType()               Returns the current record's "type" value
 * @method string             getGroupe()             Returns the current record's "groupe" value
 * @method string             getCommentaire()        Returns the current record's "commentaire" value
 * @method string             getQuantite()           Returns the current record's "quantite" value
 * @method timestamp          getCreatedAt()          Returns the current record's "created_at" value
 * @method timestamp          getUpdatedAt()          Returns the current record's "updated_at" value
 * @method RefEmplacement     getRefEmplacement()     Returns the current record's "RefEmplacement" value
 * @method WrkArrivageProduit getWrkArrivageProduit() Returns the current record's "WrkArrivageProduit" value
 * @method WrkMouvement       setIdMouvement()        Sets the current record's "id_mouvement" value
 * @method WrkMouvement       setIdUtilisateur()      Sets the current record's "id_utilisateur" value
 * @method WrkMouvement       setHeurePrise()         Sets the current record's "heure_prise" value
 * @method WrkMouvement       setRefProduit()         Sets the current record's "ref_produit" value
 * @method WrkMouvement       setBrSap()              Sets the current record's "br_sap" value
 * @method WrkMouvement       setCodeEmplacement()    Sets the current record's "code_emplacement" value
 * @method WrkMouvement       setRetry()              Sets the current record's "retry" value
 * @method WrkMouvement       setType()               Sets the current record's "type" value
 * @method WrkMouvement       setGroupe()             Sets the current record's "groupe" value
 * @method WrkMouvement       setCommentaire()        Sets the current record's "commentaire" value
 * @method WrkMouvement       setQuantite()           Sets the current record's "quantite" value
 * @method WrkMouvement       setCreatedAt()          Sets the current record's "created_at" value
 * @method WrkMouvement       setUpdatedAt()          Sets the current record's "updated_at" value
 * @method WrkMouvement       setRefEmplacement()     Sets the current record's "RefEmplacement" value
 * @method WrkMouvement       setWrkArrivageProduit() Sets the current record's "WrkArrivageProduit" value
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWrkMouvement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wrk_mouvement');
        $this->hasColumn('id_mouvement', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_utilisateur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('heure_prise', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('ref_produit', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('br_sap', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('code_emplacement', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('retry', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('groupe', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('commentaire', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('quantite', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RefEmplacement', array(
             'local' => 'code_emplacement',
             'foreign' => 'code_emplacement'));

        $this->hasOne('WrkArrivageProduit', array(
             'local' => 'ref_produit',
             'foreign' => 'br_sap'));
    }
}