<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RefChauffeur', 'doctrine');

/**
 * BaseRefChauffeur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $id_chauffeur
 * @property string $nom
 * @property string $prenom
 * @property string $num_doc_id
 * @property integer $id_transporteur
 * @property timestamp $updated_at
 * @property timestamp $created_at
 * @property RefTransporteur $RefTransporteur
 * @property Doctrine_Collection $WrkExpedition
 * @property Doctrine_Collection $WrkArrivage
 * 
 * @method int                 getIdChauffeur()     Returns the current record's "id_chauffeur" value
 * @method string              getNom()             Returns the current record's "nom" value
 * @method string              getPrenom()          Returns the current record's "prenom" value
 * @method string              getNumDocId()        Returns the current record's "num_doc_id" value
 * @method integer             getIdTransporteur()  Returns the current record's "id_transporteur" value
 * @method timestamp           getUpdatedAt()       Returns the current record's "updated_at" value
 * @method timestamp           getCreatedAt()       Returns the current record's "created_at" value
 * @method RefTransporteur     getRefTransporteur() Returns the current record's "RefTransporteur" value
 * @method Doctrine_Collection getWrkExpedition()   Returns the current record's "WrkExpedition" collection
 * @method Doctrine_Collection getWrkArrivage()     Returns the current record's "WrkArrivage" collection
 * @method RefChauffeur        setIdChauffeur()     Sets the current record's "id_chauffeur" value
 * @method RefChauffeur        setNom()             Sets the current record's "nom" value
 * @method RefChauffeur        setPrenom()          Sets the current record's "prenom" value
 * @method RefChauffeur        setNumDocId()        Sets the current record's "num_doc_id" value
 * @method RefChauffeur        setIdTransporteur()  Sets the current record's "id_transporteur" value
 * @method RefChauffeur        setUpdatedAt()       Sets the current record's "updated_at" value
 * @method RefChauffeur        setCreatedAt()       Sets the current record's "created_at" value
 * @method RefChauffeur        setRefTransporteur() Sets the current record's "RefTransporteur" value
 * @method RefChauffeur        setWrkExpedition()   Sets the current record's "WrkExpedition" collection
 * @method RefChauffeur        setWrkArrivage()     Sets the current record's "WrkArrivage" collection
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefChauffeur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_chauffeur');
        $this->hasColumn('id_chauffeur', 'int', 11, array(
             'type' => 'int',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('nom', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('prenom', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('num_doc_id', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('id_transporteur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RefTransporteur', array(
             'local' => 'id_transporteur',
             'foreign' => 'id_transporteur'));

        $this->hasMany('WrkExpedition', array(
             'local' => 'id_chauffeur',
             'foreign' => 'id_chauffeur'));

        $this->hasMany('WrkArrivage', array(
             'local' => 'id_chauffeur',
             'foreign' => 'id_chauffeur'));
    }
}