<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RefNature', 'doctrine');

/**
 * BaseRefNature
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $id_nature
 * @property string $libelle
 * @property time $delais
 * @property timestamp $updated_at
 * @property timestamp $created_at
 * @property Doctrine_Collection $WrkExpedition
 * @property Doctrine_Collection $WrkExpeditionProduit
 * @property Doctrine_Collection $WrkArrivage
 * @property Doctrine_Collection $WrkArrivageProduit
 * 
 * @method int                 getIdNature()             Returns the current record's "id_nature" value
 * @method string              getLibelle()              Returns the current record's "libelle" value
 * @method time                getDelais()               Returns the current record's "delais" value
 * @method timestamp           getUpdatedAt()            Returns the current record's "updated_at" value
 * @method timestamp           getCreatedAt()            Returns the current record's "created_at" value
 * @method Doctrine_Collection getWrkExpedition()        Returns the current record's "WrkExpedition" collection
 * @method Doctrine_Collection getWrkExpeditionProduit() Returns the current record's "WrkExpeditionProduit" collection
 * @method Doctrine_Collection getWrkArrivage()          Returns the current record's "WrkArrivage" collection
 * @method Doctrine_Collection getWrkArrivageProduit()   Returns the current record's "WrkArrivageProduit" collection
 * @method RefNature           setIdNature()             Sets the current record's "id_nature" value
 * @method RefNature           setLibelle()              Sets the current record's "libelle" value
 * @method RefNature           setDelais()               Sets the current record's "delais" value
 * @method RefNature           setUpdatedAt()            Sets the current record's "updated_at" value
 * @method RefNature           setCreatedAt()            Sets the current record's "created_at" value
 * @method RefNature           setWrkExpedition()        Sets the current record's "WrkExpedition" collection
 * @method RefNature           setWrkExpeditionProduit() Sets the current record's "WrkExpeditionProduit" collection
 * @method RefNature           setWrkArrivage()          Sets the current record's "WrkArrivage" collection
 * @method RefNature           setWrkArrivageProduit()   Sets the current record's "WrkArrivageProduit" collection
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefNature extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_nature');
        $this->hasColumn('id_nature', 'int', 2, array(
             'type' => 'int',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('libelle', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('delais', 'time', null, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('WrkExpedition', array(
             'local' => 'id_nature',
             'foreign' => 'id_nature'));

        $this->hasMany('WrkExpeditionProduit', array(
             'local' => 'id_nature',
             'foreign' => 'id_nature'));

        $this->hasMany('WrkArrivage', array(
             'local' => 'id_nature',
             'foreign' => 'id_nature'));

        $this->hasMany('WrkArrivageProduit', array(
             'local' => 'id_nature',
             'foreign' => 'id_nature'));
    }
}