<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/01/18 11:18:12
sfConfig::add(array(
  'app_sf_guard_plugin_signin_form' => 'LoginForm',
  'app_sf_guard_plugin_success_signin_url' => '@homepage',
  'app_sf_guard_plugin_liste_appli' => array (
  0 => 'app_frontend',
),
  'app_cultures_enabled' => array (
  'fr' => 'Français',
  'en' => 'English',
),
));
