<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/01/18 11:15:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=gt_log_tst_01',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
