<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/01/18 11:18:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=gt-sed',
  'username' => 'chou',
  'password' => 'azerty',
  'name' => 'doctrine',
)),);
