<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/01/18 11:15:32
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'accueil',
      ),
    ),
  ),
);
