<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/01/18 11:18:13
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'gestion des utilisateurs',
        1 => 'gestion des utilisateurs niveau 1',
        2 => 'gestion des utilisateurs niveau 2',
      ),
    ),
  ),
  'editpassword' => 
  array (
    'is_secure' => false,
  ),
  'updatepassword' => 
  array (
    'is_secure' => false,
  ),
);
