<?php

/**
 * RefEmplacement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RefEmplacement extends BaseRefEmplacement {

    const CODE_EMPLACEMENT_RECEPTION = "Réception";
    const LIBELLE_EMPLACEMENT_RECEPTION = "Réception centrale";

}
